#!/bin/sh

# Usage: farm_list
#
# This script creates batch_krun and jscript_krun in batch_files directory
# and submits the job to the farms
#
# Feb. 22, 2011 Zhihong Ye
#
RAWDIR=/w/cache/mss/halla/e07006/raw/
home=/work/halla/e08014/disk1/yez
#home=$(PWD)                    # The directory where replay_script is

# Event you want to start with,gtotal=-1 means to replay all
gstart=1
#gtotal=50000
gtotal=-1


username=${USER}@jlab.org    # email which will be notify when the job is done

#
# Check whether the raw data are in cache or not
#
echo "&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&"
echo "& Before you submit the jobs, you need to make sure that the  &"
echo "& raw data are already in the/w/cache/mss/halla/e07006/raw/   &"
echo "&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&"
echo " "
test=0
echo "Are thy already in /cache/mss/? 1->Yes, 0->No or Not Sure"
read test

if [ "$test" -eq 0 ]
then 
    echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
    echo "%    Please run:  ifarml3>./farm_cache [runlist]         %"
    echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
    exit 1
else
    if [ "$test" -eq 1 ]
    then
	clear
	echo
	echo "Good! Lets start to submit the job!"
	echo
    fi
fi
#
# Function to check if input is an integer
#
is_integer() {
 case $1 in
  *[!0-9]*) return 1;;
  *) return 0;;
 esac
}


#
# Verify if batch_files and .tmp.REPLAY exist
#
if ! [ -d batch_files ]
    then 
    echo "----------------------------------------------------------------"
    echo "I need batch_files directory. I am going to create it"
    echo  
    mkdir batch_files
fi
#
# Ask for file name
#
echo "----------------------------------------------------------------"
echo "Input the file name. It needs a list of run numbers(ex, runlist.dat)"
echo 
echo -n "File name: "
read fname

#
echo
while read krun
  do
  echo "Working on run "${krun}
  echo "---------------------"
#
# Write file batch_krun
#
  rm -f batch_files/batch_${krun}
  echo "#!/bin/sh" > batch_files/batch_${krun}
  echo "cd " ${home}"/replay" >>batch_files/batch_${krun}
  echo "rm -f ./Rootfiles/e07006_HRS_"${krun}"*.root" >>batch_files/batch_${krun}
  echo " ">>batch_files/batch_${krun}
  echo "analyzer -q -d 'replay_HRS.C("${krun}","${gtotal}","${gstart}")'">>batch_files/batch_${krun}
     
#  
  chmod +x batch_files/batch_${krun}
  
  echo "batch_files/batch_"${krun}" has been created!"
  echo " "

#
# Write the jsub script
#
  rm -f batch_files/jscript_$krun
  echo "PROJECT     e07006" > batch_files/jscript_$krun
  echo "COMMAND     "$home"/batch_farm/batch_files/batch_"$krun >>batch_files/jscript_$krun
  echo "JOBNAME     src.analysis"${krun} >>batch_files/jscript_$krun
  echo "TRACK       analysis" >> batch_files/jscript_$krun
  echo "TIME        4000" >>batch_files/jscript_$krun
  echo "MEMORY      1800 MB" >>batch_files/jscript_$krun
  echo "OS          linux" >>batch_files/jscript_$krun
  echo "MAIL:       "$username >>batch_files/jscript_$krun
 # echo "INPUT_FILES:"$home"/replay/HRS.odef" >>batch_files/jscript_$krun
 
  echo "batch_files/jscript_"${krun}" has been created."
  echo " " 
  echo "Now, let us wait for the farms..."
  echo " "
#
# Submit job to the farm
  jsub batch_files/jscript_$krun
#
#
  echo "Job "$krun "has been submited!"
  echo
  echo
#
  sleep 1
done < $fname
echo
echo "***** Good Bye and thank you for using the script *****"
echo
